### ISSUE TITLE
`Call to a member function direction() on null`

### ISSUE THREAD

**Issue by afbora** [zephir/kirby-cookieconsent#4]
I'm getting following error on single language app:

> Call to a member function direction() on null
> \kirby-cookieconsent\src\Configuration.php:29

Plugin version 3.0.0
Kirby version 4.1.0

**Comment by TheMaaarc** [comment]
Sorry about that, I completely missed the single language bug.
I fixed the issue and released a new version (3.1.0).

You can now set your language in the plugin options:

```php
'zephir.cookieconsent' => [
    'language' => [
        'locale' => 'de', // The translation to use, default is en
        'direction' => 'ltr' // Either ltr or rtl, default is ltr
    ]
]
```

**Comment by afbora** [comment]
Thank you. I already switched to custom js service, sorry 🙈 You can close the issue 👍

**Comment by TheMaaarc** [comment]
No worries, thanks for repporting the bug :)
